### PR TITLE
secure websockets / remote player support

### PR DESCRIPTION
**Pull request by t3chman**
CFX/NUI requires secure connections for remote endpoints that aren't localhost. This adds support for WSS instead of WS. Unfortunately, CFX/NUI also don't accept self-signed certs for the same reason, so you must have a CA generated cert for the domain used as the endpoints. This is the only way to get remote client support for production or otherwise.

Also minor changes to server.cfg so that local.cfg can override other default parameters and removed the fivem ace identifier defined.

Feel free to make changes to this as you see fit of course. I started trying to maintain an insecure option as originally implemented, but seeing as it doesn't support any remote player connections, I figure that's not very valuable moving forward.

### CODE REVIEW

**Comment by spAnser** [comment]
Are the example certs just self signed ones that don't work?

**Comment by spAnser** [comment]
I also think depending on how you ultimately setup the server. The cert may not even be managed by the socket server itself.
It might reside behind a reverse proxy.
I've been using Caddy lately for the automated SSL certs it can manage for you.

My current local dev is proxied through cloudflare where that manages a ssl cert for me and I still will run the socket server in insecure mode.

I think an option to use secure or not via `.env` variable is probably the best option.

I should probably look at writing a README specifically for the socket folder to outline possible solutions and paths.

**Comment by t3chman** [comment]
The example cert (from the example key) is a self-sign yeah, but just included it to show the format as I know many don't have any experience with SSL and figured it might curb some confusion/questions.

Yeah, on the note of making an option in `.env`, I had started that and then ceased as it gets a bit more complex since you either need to use http or the https module and cert/key. Not too difficult though of course and I'll update the PR sometime when I get a chance.

I agree though on docs about how the socket server/clients work and solutions for use. I'm used to working with this sorta thing, but most aren't. Regardless, appreciate the share and effort thus far!

**Comment by spAnser** [comment]
I think I will close this for now. I'm not sure if anyone is still having issues with this.

But if it is an issue we should probably offer an option not a hard choice for the user.

**Pull request closed without merging**
